### ISSUE TITLE
Automate release to GitHub

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-rest-api#44] opened 2021-11-29 12:36 UTC
Automate the release process for GitHub

**Comment by pj-spoelders** [comment] 2021-12-02 12:45
There currently is a workflow made by Nastya that uploads the generated build artifacts to the release. 
(It prompts the user for the upload_url of the release, which we have to make manually first),
It can be included/adapted.

**Comment by pj-spoelders** [comment] 2022-01-06 14:51
After having a closer look this workflow was intended to be used by/with release-droid.

**Comment by pj-spoelders** [comment] 2022-01-06 14:52
TBD

**Comment by pj-spoelders** [comment] 2022-08-08 08:26
This seems to work as intended right now. Succesfully made a release last week. Closing this ticket. Thanks @kaklakariada & others who worked on this.

**Closed by pj-spoelders** 2022-08-08 08:26 UTC
Labels: source:exasol, refactoring
